"""
Constants.py
"""
S3_SOURCE_BUCKET = "heb-stg-emd-store-raw-ora.pemd"
DELTA_RAW_PREFIX = "delta_raw/"

S3_CK_COLL_CNTL_PREFIX = "emd-ck-coll-cntl"
S3_CMPTR_TYP = "emd-cmptr-typ"
S3_COMPANY = "emd-company"
S3_DIST = "emd-dist"
S3_ECOMM_MKT_AREA = "emd-ecomm-mkt-area"
S3_FINANCIAL_DIV = "emd-financial-div"
S3_FRNT_END = "emd-frnt-end"
S3_LIN_OF_BUS = "emd-lin-of-bus"
S3_LOCATION_TYP = "emd-location-type"
S3_MKT_RGN = "emd-mkt-rgn"
S3_RETL_LOC_FRMT = "emd-retl-loc-frmt"
S3_RETL_LOC_SEGM = "emd-retl-loc-segm"
S3_RETL_LOC_STAT_TYP = "emd-retl-loc-stat-typ"
S3_RETL_LOC_TYP = "emd-retl-loc-typ"
S3_RETL_UNLD = "emd-retl-unld"
S3_SRS_SYS = "emd-srs-sys"
S3_STR_OPSTMT_HDR_TYP = "emd-str-opstmt-hdr-typ"
S3_STR_OPSTMT_TYP = "emd-str-opstmt-typ"

S3_RETAIL_LOC ="firehose-emd-retail-loc"
S3_LOCATION="firehose-emd-location"
S3_HEB_DT="firehose-emd-heb-dt"
S3_STR_OPSTMT_SRT_CD="firehose-emd-str-opstmt-srt-cd"

PK_LIN_OF_BUS = "LIN_OF_BUS_ID"
PK_COMPANY = "COMPANY_ID"
PK_CK_COLL_CNTL = "CK_COLL_CNTL_CD"
PK_CMPTR_TYP = "CMPTR_TYP_CD"
PK_DIST = "DIST_ID"
PK_ECOMM_MKT_AREA = "ECOMM_MKT_AREA_CD"
PK_FINANCIAL_DIV = "FINANCIAL_DIV_ID"
PK_FRNT_END = "FRNT_END_CD"
PK_LOCATION_TYPE ="LOC_TYP_CD"
PK_MKT_RGN="MKT_RGN_ID"
PK_RETL_LOC_FRMAT="RETL_LOC_FRMAT_CD"
PK_RETL_LOC_SEGM="RETL_LOC_SEGM_CD"
PK_RETL_LOC_STAT_TYP="RETL_LOC_STAT_CD"
PK_RETL_LOC_TYP = "RETL_LOC_TYP_CD"
PK_RETL_UNLD="RETL_UNLD_CD"
PK_SRS_SYS="ON_SRS_CD"
PK_STR_OPSTMT_HDR_TYP="STR_OPSTMT_HDR_CD"
PK_STR_OPSTMT_TYP="STR_OPSTMT_TYP_CD"

PK_HEB_DT = "DT_ID"
PK_LOCATION = "LOC_TYP_CD, LOC_NBR"
PK_RETAIL_LOC = "LOC_TYP_CD, LOC_NBR"
PK_STR_OPSTMT_SRT_CD ="STR_OPSTMT_SRT_CD"
